### ISSUE TITLE
问题：output_arrays 'finetune_mrc/add, finetune_mrc/add_1' 中的add_1找不到

### ISSUE THREAD

**Issue by haojiepan1** [CLUEbenchmark/MobileQA#1]
您好，最近在github上看到您开源的MobileQA，按照您的流程在pb文件转tflite文件时遇到了问题，无法转换成功，问题出在 output_arrays 'finetune_mrc/add, finetune_mrc/add_1' 中的add_1找不到，希望能够得到您的帮助。万分感谢！

**Comment by Kay-Tian** [comment]
@haojiepan1 请问这个问题是如何解决的？我也遇到这个问题。

**Comment by alexhuahua** [comment]
中间多了个空格，所以找不到了，但是我去掉空格以后还是报错，
Traceback (most recent call last):
  File "/Users/asrock/opt/anaconda3/envs/py36/bin/tflite_convert", line 8, in <module>
    sys.exit(main())
  File "/Users/asrock/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 515, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/Users/asrock/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/asrock/opt/anaconda3/envs/py36/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/Users/asrock/opt/anaconda3/envs/py36/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/asrock/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 511, in run_main
    _convert_tf1_model(tflite_flags)
  File "/Users/asrock/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 199, in _convert_tf1_model
    output_data = converter.convert()
  File "/Users/asrock/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 983, in convert
    **converter_kwargs)
  File "/Users/asrock/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 449, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/Users/asrock/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-11-06 17:52:53.956209: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: SparseSoftmaxCrossEntropyWithLogits
2020-11-06 17:52:53.956239: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: SparseSoftmaxCrossEntropyWithLogits
2020-11-06 17:52:53.975861: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 757 operators, 1442 arrays (0 quantized)
2020-11-06 17:52:53.991763: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 757 operators, 1442 arrays (0 quantized)
2020-11-06 17:52:53.992624: F tensorflow/lite/toco/graph_transformations/resolve_constant_gather.cc:51] Check failed: stride * coords_shape.dims(0) == output_data.size() (128 vs. 65536)
Fatal Python error: Aborted

Current thread 0x0000000109ec65c0 (most recent call first):
  File "/Users/asrock/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52 in execute
  File "/Users/asrock/opt/anaconda3/envs/py36/lib/python3.6/site-packages/absl/app.py", line 251 in _run_main
  File "/Users/asrock/opt/anaconda3/envs/py36/lib/python3.6/site-packages/absl/app.py", line 300 in run
  File "/Users/asrock/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40 in run
  File "/Users/asrock/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89 in main
  File "/Users/asrock/opt/anaconda3/envs/py36/bin/toco_from_protos", line 8 in <module>
